spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.190.202.223:3306/dbgirl2?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: 841114Waff!_

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 80

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-like: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false